on: #指定触发 workflow 的事件
  workflow_dispatch: #当代码推送时触发

jobs: #定义工作流程
  build: #工作流名称为 build
    runs-on: ubuntu-22.04 #使用 Ubuntu 22.04 环境执行
    container: #定义容器
      image: archlinux:latest #使用 Arch Linux 镜像
    steps: #定义工作流程中的步骤
      - name: Install dependencies
        run: |
          pacman -Syyu --noconfirm \
            base-devel \
            arm-none-eabi-gcc \
            arm-none-eabi-newlib \
            git \
            python-pip \
            python-crcmod \
            zip \

      - name: Checkout #拉取代码
        uses: actions/checkout@v4 #使用 GitHub Actions 提供的 checkout 动作

      - name: safe.directory #设置 git 的 safe.directory 配置
        run: git config --global --add safe.directory /__w/uv-k5-firmware-custom/uv-k5-firmware-custom

      - name: Generate #生成固件
        run: |
          make build_all ENABLE_CHINESE_FULL=4 ENABLE_MESSENGER=1 ENABLE_MESSENGER_DELIVERY_NOTIFICATION=1 ENABLE_MESSENGER_NOTIFICATION=1 ENABLE_DOPPLER=1 ENABLE_MDC1200=1 ENABLE_MDC1200_EDIT=1 ENABLE_MDC1200_CONTACT=1 ENABLE_PINYIN=1 ENABLE_SPECTRUM=1

      - name: Create ZIP file
        run: |
            mkdir -p output
            zip -j output/losehu.zip ./*.bin 

      - name: Upload ALL #上传固件文件
        uses: actions/upload-artifact@v4 #使用 GitHub Actions 提供的 upload-artifact 动作
        with:
          name: firmware_all #设置 artifact 名称为 firmware
          path: output/losehu.zip #上传文件路径为 LOSEHU*.bin
